# Site settings
title: 探索良质之地
SEOTitle: 虫壳
header-img: img/post-bg-desk.jpg
email: tel17321315891@gmail.com
description: ""
keyword: "SolarPhi, 虫壳"
url: "https://SolarPhi.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
# Sidebar settings
sidebar: true
sidebar-about-description: "幸福不过是一个接着一个的欲望"
# SNS settings
RSS: true
zhihu_username: 汤博未
github_username: SolarPhi
telegram_username: @SolarPhi
