# Site settings
title: BY Blog
SEOTitle: 虫壳 | BY Blog
header-img: img/post-bg-desk.jpg
email: qiubaiying@gmail.com
description: "Every failure is leading towards success."
keyword: "SP, SP Blog, 虫壳"
url: "https://SolarPhi.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
# Sidebar settings
sidebar: true
sidebar-about-description:"幸福不过是一个接着一个的欲望"
# SNS settings
RSS: true
zhihu_username: 汤博未
